### ISSUE TITLE
Colab Notebook not working

### ISSUE THREAD

**Issue by luca-venturini** [vinthony/ghost-free-shadow-removal#48]
Hello, 

When I try to run the provided notebook I stuck into the following error, when it tries to import tensorflow:

[ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory](url)

How can I solve the problem?

Thanks

**Comment by muumimorko** [comment]
First way I found was to downgrade Cuda to 10.0
add `!apt install cuda-10-0` where installing other prerequisites.

**Comment by vinthony** [comment]
solved by @muumimorko

**Comment by heorhiikalaichev** [comment]
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package cuda-10-0
Found existing installation: tensorflow 2.12.0
Uninstalling tensorflow-2.12.0:
  Successfully uninstalled tensorflow-2.12.0
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libcudnn7
ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==1.13.1 (from versions: 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.12.0)
ERROR: No matching distribution found for tensorflow-gpu==1.13.1
Listing... Done
Fri Aug  4 14:26:24 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-2-ffe8430e3bc9>](https://ifukv6cbcxo-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230802-060128-RC00_553100604#) in <cell line: 16>()
     14 get_ipython().run_line_magic('matplotlib', 'inline')
     15 
---> 16 import tensorflow as tf
     17 import numpy as np
     18 import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'tensorflow'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
