### ISSUE TITLE
unable to download the pretrained model

### ISSUE THREAD

**Issue by evanlym** [vinthony/ghost-free-shadow-removal#8]
Hi! Thanks for the great work and sharing the source code!
I had some trouble downloading the pretrained model from OneDrive. It seems that the file has exceeded the size limit. Instead of model_best.ckpt.data, I got a txt file saying "File is too big to download. Requested File Size: 99 MB, Max File Size Limit: 25 MB".
I didn't see others complaining about the same problem, so it could be my fault, but do you have any clue what are the possible reasons? Or is it possible for you to share it on google drive?
Moreover, by pretrained-vgg19, do you mean the file imagenet-vgg-verydeep-19?

Thanks!

**Comment by evanlym** [comment]
I found the google drive link on the Colab code, sorry for the disturbance

**Comment by vinthony** [comment]
Hi, thanks for your attention.
the pre-trained vgg19 the pre-trained model here: https://www.vlfeat.org/matconvnet/models/imagenet-vgg-verydeep-19.mat
I am sorry I might not share all the links on google drive recently.
Because of COVID 19, I am in mainland China which can not access the google drive.
I will update all the pre-trained models when I have the change to back school.
sorry for the inconvenience.

**Comment by evanlym** [comment]
Thank you for your timely reply! Good luck and stay safe^^

**Comment by vinthony** [comment]
thanks! you too!
